version: "3.7"
services:
  balena-cli:
    build:
      context: .
      dockerfile: Dockerfile.balena-cli

    user: "node"
    working_dir: /home/node

    init: true

    volumes:
      - ./balena_cli_configs:/home/node/.balena
      - ./ssh-keys:/home/node/.ssh
      - ./scripts:/home/node/scripts
      - ./staged-releases:/home/node/staged-releases
      
    stdin_open: true
    tty: true

    command: "/bin/bash" 