FROM node:8-jessie
RUN apt-get update && apt-get install -y python build-essential git rsync jq curl sudo vim && rm -rf /var/lib/apt/lists/*
RUN npm install balena-cli -g --production --unsafe-perm
RUN curl -L https://raw.githubusercontent.com/balena-io/balena-cli/master/balena-completion.bash -o /etc/bash_completion.d/balena-completion.bash
# Adding support to change to root user without password.
RUN echo node ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/node \
    && chmod 0440 /etc/sudoers.d/node
CMD ["/bin/bash"]